### ISSUE TITLE
"Terms & conditions" not working

### ISSUE THREAD

**Issue by enriqueddm** [BorislavZlatanov/TVP-website#14]
The registration process doesn't let you continue until you accept "Terms and conditions" but if you follow the link to read them it shows an empty popup. 
I don't care too much about terms and conditions, but it doesn't look good for general public that it forces you to accept some blank terms and conditions.

I would think that we have to add the correct terms and conditions for the website or, if we don't have them yet, to completely remove the "term and conditions" link, check-box and validations

**Comment by BorislavZlatanov** [comment]
Maybe this was something temporary. The Terms & Conditions are displaying alright at the moment.
