### ISSUE TITLE
Add numbers to the FAQs

### ISSUE THREAD

**Issue by BorislavZlatanov** [BorislavZlatanov/TVP-website#16]
We received a request to add numbers to the FAQs on this page: https://www.thevenusproject.com/faq

We'll have to look at the best way to accomplish this (without manually entering those numbers, of course).

**Comment by xhyderz** [comment]
Add a prefix to the HTML attr of the elements by looping through the child
elements. It can be easily accomplished.

**Comment by BorislavZlatanov** [comment]
This has been implemented on the site. :)
