### ISSUE TITLE
Contact forms not functioning

### ISSUE THREAD

**Issue by SGillessen** [BorislavZlatanov/TVP-website#17]
I just received a Skype message reporting the contact forms at https://www.thevenusproject.com/en/contact not working

**Comment by SGillessen** [comment]
Additional Information:

The bug was noticed when the person tried to check the checkbox "send me a copy" and didn't receive a copy upon submitting the message

**Comment by BorislavZlatanov** [comment]
When submitting the contact form there, I get the message "SMTP connect failed". This implies that the mailing account or settings are not set up properly.

**Comment by SGillessen** [comment]
Please update the SMTP settings at https://www.thevenusproject.com/administrator/index.php?option=com_config#page-server

**Comment by BorislavZlatanov** [comment]
Contact forms seem to be working now.
